### ISSUE TITLE
Remover `.env`

### ISSUE THREAD

**Issue by joaoseckler** [franpessoa/LOXLoadingComplete#2]
Os tokens do seu bot deveriam ficar escondidos e não publicados aqui no github. Veja a [documentação](https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token):

> Note that this token should be kept private, and must be reset if it is leaked

Dica: depois de remover o arquivo do git (`git rm .env` e etc) você pode criar um arquivo `.gitignore` na pasta do seu projeto e adicionar a ele a linha

`.env`

Isso vai dizer ao git que ele tem que ignorar o arquivo `.env`!

**Comment by franpessoa** [comment]
Acho que foi corrigido. O .env foi deletado e o 'README.md' tem instruções de como criar um. Eu deixo essas instruções pois meu código roda no Replit, onde contas gratuitas tem todo o seu código aberto, exeto pelo .env
